name: master-deploy-action

on:
  pull_request:
    branches:
      - main
      - develop
    paths-ignore:
      - './README.md'
      
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - './README.md'

env:
  IMAGE: taewakim/need_backend_server:latest
  CONTAINER: backend_server

permissions:
      id-token: write
      contents: read
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Chackout
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Set up Application Configuration
        run: echo "${{ secrets.APPLICATION_Config }}" > ./src/main/resources/application.yml
      
      - name: Build
        run: ./gradlew build -x test
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Publish Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: $IMAGE

  deploy:
    runs-on: [ self-hosted, label-go ]
    needs: build
    
    steps:
      - name: Docker Pull
        run: |
          docker stop $CONTAINER && docker rm $CONTAINER
          docker rmi $IMAGE
          docker image pull $IMAGE
          docker run -dp 8080:8080 --name $CONTAINER $IMAGE
          
