name: master-deploy-action

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - './README.md'
      - './github/*'
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Chackout
        uses: action/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Test
        run: ./gradlew test
      
      - name: Build
        run: ./gradlew build
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Publish Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: taewakim/need_backend_server
