name: master-deploy-action

on:
  pull_request:
    branches:
      - main
      - develop
    paths-ignore:
      - './README.md'
      - './github/*'
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - './README.md'
      - './github/*'
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Chackout
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Set up Application Configuration
        run: echo "${{ secrets.APPLICATION_Config }}" > ./src/main/resources/application.yml
      
      - name: Build
        run: ./gradlew build -x test
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Publish Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: taewakim/need_backend_server:latest
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::620876430593:role/GitHubAction-AssumeRoleWithAction
          aws-region: ap-northeast-2a
      
      - name: Docker Pull & Docker Image Run
        run: ls -al
#           docker pull taewakim/need_backend_server:latest
#           docker run -dp 8080:8080 taewakim/need_backend_server:latest
