name: manual

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean

permissions:
      id-token: write
      contents: read
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Chackout
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Set up Application Configuration
        run: |
          mkdir ./src/main/resources
          echo "${{ secrets.APPLICATION_CONFIG }}" > ./src/main/resources/application.yml
      
      - name: Build
        run: ./gradlew build -x test
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Publish Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: taewakim/need_backend_server:latest

  deploy:
    runs-on: [ self-hosted, label-go ]
    needs: build
    
    steps:
      - name: Docker Pull
        run: |
          docker stop backend_server && docker rm backend_server
          docker rmi taewakim/need_backend_server:latest
          docker image pull taewakim/need_backend_server:latest
          docker run -dp 8080:8080 --name backend_server taewakim/need_backend_server:latest
      
      - name: Send messages to Slack
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          author_name: Need-Backend Deploy
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
